# -*- coding: utf-8 -*-
"""tasks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-rgQJcWpA9TxwsUBZU-labf5thjwZCT
"""













a = 3
b = 4
print((a**2 + b**2)**0.5)

name = 'MARIAM'
her_name = f'My name is {name.capitalize()}'
print(her_name)

name = "Susan"
age = "young"
gender = "lady"
school = 'CLRWY IT University'
message = (
    f"{name} is a {age} {gender}. "
    f"And she is a student at the  {school} "

)
print(message)

city = "SAREJEVO"
message = f"I live in {city.capitalize()}."
print(message)

print("{}! I am {} programmer and I {} Clarusway.".format("Hello", "new", "love"))

text = "the better the family, the better the society"
print(text.title())

text = "S0d0me and G0m0re"
text = text.replace("0", "o")
print(text)

# 1. soru STRİNGİN İLK ORTA VE SON KARAKTERİNİ YAZDIR.
text = "GÜLSÜME"
print(text[::3])

#  2. soru STRİNGİN İLK 2 VE SON 2 KARAKTERİNİ YAZDIR.
print(text[:2] + text[5:])

#  3. soru İKİ STRİNGTE BAŞLARDAKİ İKİ KARAKTERLERİN YERİNİ DEĞİŞTİR.
 string1 = "glm"
 string2 = "esg"
 print(string1, string2)
 print(string2[:2] + string1[2:] + " " + string1[:2] + string2[2:])

# 4. soru İKİ STRİNG SAYIYI TOPLA VE ÇIKTI DA STRİNG OLSUN.
no1 = "1900"
no2 = "96"
sum = int(no1) + int(no2)
print(str(sum))
print(type(str(sum)))

#  5. soru  VERİLEN İFADEDE İLK VE SON KARAKTERLERİN YERİNİ DEĞİŞTİR.
 false_name = "mülsüg"

 true_name = false_name[5] + false_name[1:5] + false_name[0]

 print(true_name)

#  6. soru VERİLEN STRİNGTE İNDEXİ TEK OLANLARI SİL KALANLARI YAZDIR.
 name ="GÜLSÜM"
print(name[::2])

listem = [1, 2, 3, 4]
listem.insert(4, 5)
print(listem)

user = int(input("lütfen bir sayı giriniz : "))
listem = list(range(1,user+1,2))
print(listem)

name = input("Adınızı ve soyadınızı giriniz : ").upper()

name_new = name.split()
name_new_1 = name_new[0][0]
name_new_2 = name_new[1][0]

print(name_new_1 + "." + name_new_2 + ".")

ailem = {
    "mom": "gülendam",
    "dad": "hasan",
    "brother": "emre",
    "sister": "hilal",
}

print(ailem)

ailem = {
    "mom": "gülendam",
    "dad": "hasan",
    "brother": "emre",
    "sister": "hilal",
}
ailem["fındılımmmm"] = "eren"
print(ailem)

print(list(ailem.items()))
print(list(ailem.keys()))
print(list(ailem.values()))

ailem = {
    "mom": "gülendam",
    "dad": "hasan",
    "brother": "emre",
    "sister": "hilal",
}
ailem.update({"damat":"mehmet"})
print(ailem)

arkadaşlarım = {
     'canım1': {"adı":"kumbüş", "lakabı": "kup"},
    'canım2':  {"adı": "meskoş", "lakabı": "koca kafa"},
    'canım3':  {"adı": "ayşegül", "lakabı": "kadın"},
    'canım4':  {"adı": "kübra", "lakabı": "ablacım"},
    'canım5':  {"adı": "şeyma", "lakabı": "dik burunlu"}
}
print(arkadaşlarım)

benimkiler = {
    "friends": {"friend1": {"name": "kübra", "age": "28"},
                "friend2": {"name": "mesken", "age": "29"},
                "friend3": {"name": "aysegül", "age": "29"},
    },
    "family": { "mom": {"name": "gülendam", "age": "50"},
               "dad": {"name": "hasan", "age": "55"},
              "brother": {"name": "emre", "age": "30"}
    }}

print(benimkiler)

biyoloji = input("Bir DNA dizisi giriniz: ").upper()

print("RNA:", biyoloji.replace("T","U"))

user = input("lütfen yes veya no yazın:").upper()

sonuc = user.upper() == "YES"
print(sonuc)

user = input("lütfen yes veya no yazın:").upper()

sonuc = user.upper() == "YES"
print(sonuc)

num = int(input("Lütfen bir sayı giriniz:"))
if num > 0 :
  print("girdiğiniz değer pozitif bir sayı")
elif num < 0:
  print("girdiğiniz değer negatif bir sayı")
else:
  print("girdiğiniz değer sıfıra eşit")

yüzyıl = int(input("İstediğiniz bir yılı giriniz:"))
if yüzyıl % 100 == 0:
  print(yüzyıl, ".yüzyıldasınız")
else:
  print(yüzyıl // 100 + 1, ".yüzyıldasınız")

sayı = int(input("Aklına ilk gelen sayıyı gir:"))
print(sayı < 0 and "sayı negatif" or sayı == 0 and "sayı sıfıra eşit" or sayı > 0 and "sayı pozitif")

sayı = int(input("İstediğiniz yılı giriniz:"))
if sayı % 4 == 0:
  if sayı % 100 == 0:
    if sayı % 400 == 0:
      print("Girdiğiniz yıl artık yıl")
    else:
      print("Girdiğiniz yıl artık yıl değil.")
  else:
    print("Girdiğiniz yıl artık yıl.")
else:
  print("Girdiğiniz yıl artık yıl değil.")

for i in range(1,100):
 if i % 15 == 0:
  print("fızzbuzz")
 elif i % 3 ==0:
  print("fızz")
 elif i % 5 == 0:
  print("buzz")

 else:
  print(i)

sayı = int(input("Aklınıdan geçen bir sayıyı girin:"))
count = 0
for i in range(1,sayı+1):
  if sayı % i == 0:
    count += 1
  else:
    count += 0
if count < 3 :
  print("asal sayıdır.")

else:
  print("asal sayı değildir.")

sayı = int(input("Aklınızdan geçen bir sayıyı girin:"))
if sayı <= 1:
    print("Asal sayı değildir.")

for i in range(2, sayı):
    if sayı % i == 0:
        print("Asal sayı değildir.")
        break
else:
    print("Asal sayıdır.")

a = 0
for i in range (1,75):
  a +=i
print(a)



